require 'rake'
require 'yaml'

$project = YAML.load(File.read "#{File.dirname(__FILE__)}/../../project.yml")
$base_dir = ENV['GEOSPIN_PROJECT_BASE_DIR'] ? ENV['GEOSPIN_PROJECT_BASE_DIR'] : "/tmp/#{$project['project']}"

# Add run=dry to see shell $commands
# Example: rake stage run=dry

#####################################################################
# Variables

# The tasks will add shell commands to this empty global array
$commands = []

#####################################################################
# Default task

task :default do
  sh 'rake --tasks', verbose: false
end

#####################################################################
# Import Rakefiles from rake subfolders

Dir.glob("**/Rakefile").each do |rakefile|
  unless rakefile == 'rake/meta/Rakefile' or rakefile == 'Rakefile'
    import rakefile
  end
end

#####################################################################
# Final task

# Detect run=dry command line parameter
dry_run = false
if ENV['run'] == 'dry'
  dry_run = true
end

# if Rakefile is invoked with run=dry
# then print commands
# else run commands
task :finally do
  $commands.each do |command|
    if dry_run
      puts command
    else
      sh command
    end
  end
end

# Run final task at exit
at_exit { Rake::Task[:finally].invoke if $!.nil? }
#####################################################################
